"""empty message

Revision ID: b18c75e91daf
Revises: ece532607554
Create Date: 2022-11-28 19:17:16.117687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18c75e91daf'
down_revision = 'ece532607554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('days_off_date_key', 'days_off', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('days_off_date_key', 'days_off', ['date'])
    # ### end Alembic commands ###
