"""add employees_days_off table

Revision ID: 6e4be2d8c295
Revises: 5ed387da7a1b
Create Date: 2022-11-22 09:48:33.453307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4be2d8c295'
down_revision = '5ed387da7a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_days_off',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('day_off_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_off_id'], ['days_off.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'day_off_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_days_off')
    # ### end Alembic commands ###
