"""add employees_days_off_table

Revision ID: b2f21d4ce7f7
Revises: f180096beb01
Create Date: 2022-11-17 16:19:48.007334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f21d4ce7f7'
down_revision = 'f180096beb01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_days_off',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('day_off_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_off_id'], ['days_off.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'day_off_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_days_off')
    # ### end Alembic commands ###
