"""empty message

Revision ID: 1ae2fb2698c3
Revises: bef59dcbcb72
Create Date: 2022-11-17 11:43:57.628594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae2fb2698c3'
down_revision = 'bef59dcbcb72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('days_off',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_of_week', sa.String(length=28), nullable=False),
    sa.Column('date', sa.String(length=28), nullable=False),
    sa.PrimaryKeyConstraint('id', 'date')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('extension', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('schedule',
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('scheduler_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'employee_id', 'assignment_id')
    )
    op.create_table('employees_days_off',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('day_off_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_off_id'], ['days_off.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'day_off_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_days_off')
    op.drop_table('schedule')
    op.drop_table('employees')
    op.drop_table('days_off')
    op.drop_table('assignments')
    # ### end Alembic commands ###
