"""add day_off model

Revision ID: f180096beb01
Revises: 4b50e32dab95
Create Date: 2022-11-17 16:17:30.363540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f180096beb01'
down_revision = '4b50e32dab95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_off',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_of_week', sa.String(length=28), nullable=False),
    sa.Column('date', sa.String(length=28), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_off')
    # ### end Alembic commands ###
